### ISSUE TITLE
there is duplicate update for pda

### ISSUE THREAD

**Issue by satiparpar** [Microflow-xyz/pokt-governance-stakers#2]
Assume 1 :  there is only 1 pda on MyGateway and pda's data is = custodian, Validator 
and there is only this pda.
Assume 2 :  we only get data of  one node  from poktscan and it's data are just the same as pda that we got from MyGateway .
lets run the code ...
because the   pda is related  to that service domain , code updates the pda ( line 144 / core.service.ts).
till now every thing is ok!
let's keep going... code runs setNonCustodianActions function and because none of non-custodian coditions are true , we have line 180 in front of us, that pda will be updated again with point 0!
Is it right?

**Comment by ahmadyazdanii** [comment]
@satiparpar, Thank you for sharing this problem.
I've fixed that in commit 638f13a4ae5759b6a01ff45642b7b2323b3a15f9.
